### ISSUE TITLE
Cocoapod iOS version change

### ISSUE THREAD

**Issue by cillyfly** [jinSasaki/InAppPurchase#22]
I used InAppPurchase in my podspec and this error shows 
>  ERROR | [iOS] xcodebuild:  InAppPurchase/Sources/Product.swift:66:28: error: 'PeriodUnit' is only available on iOS 11.2 or newer

so can you change the '  s.platform     = :ios, '9.0'' to "  s.platform     = :ios, '11.2' "  in InAppPurchase.podspec 

thank you

**Comment by jinSasaki** [comment]
@cillyfly 
I cannot reproduce that.
Please tell me about your environment.

- CocoaPods version
- Podfile/Podfile.lock
- Xcode version
- Your project deployment target

**Comment by jinSasaki** [comment]
I resolved this issue!
Please use `2.1.2` or a newer. 😄
