### ISSUE TITLE
'PeriodUnit' is only available on iOS 11.2 or newer

### ISSUE THREAD

**Issue by erf** [jinSasaki/InAppPurchase#24]
When i try to build a project with deployment target 9, i get a compile error:
```
Product.swift:66:28: 'PeriodUnit' is only available on iOS 11.2 or newer
```
Your readme says the requirement is `iOS 9.0+`.

I'm on macOS Mojave, Xcode 10.

**Comment by erf** [comment]
Thanks!

**Comment by jinSasaki** [comment]
@erf  
I resolved this issue!
Please use `2.1.2` or a newer. Thanks! 😄
