### ISSUE TITLE
Restore with product ids

### ISSUE THREAD

**Issue by erf** [jinSasaki/InAppPurchase#26]
If you do a restore purchase call, how do you know which product ids were restored? Do you have to do a `fetchProduct` first and then assume all those ids were restored if a `restore` call was success? Would it be possible to add a list of product ids in the `restore` sucess call?

**Comment by jinSasaki** [comment]
@erf 
After restored, the receipt in the device has the correct and latest status.
I recommend you to fetch product ids from the receipt if you want to use user's latest status.

However, I think it is also helpful that the restore's response has product ids.
I will think about it in the next version. Thanks!
