### ISSUE TITLE
Save set of purchased items

### ISSUE THREAD

**Issue by erf** [jinSasaki/InAppPurchase#27]
Have you considered keeping a set or list of purchased/restored product ids? Also saved to disk. Or is this out of the scope of this library?

**Comment by jinSasaki** [comment]
@erf 
The purchased items and the latest status are included in the receipt. You can fetch the items from the receipt.

This library does not support the local receipt validation, (Apple recommends not to make the validation codes open source.)
but I plan to support the remote validation via Apple's receipt server in the future.

**Comment by erf** [comment]
I'm not sure i understand what `receipt` you refer to, is this part of your lib? Can you give an example?

**Comment by jinSasaki** [comment]
Each app has a receipt including In-App-Purchase information. Please read [Receipt Validation](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Introduction.html).

**Comment by erf** [comment]
I will have to read up on it, but is it not possible / simpler for the user to save the purchased items on the device after each Purchase / Restore? So you don't have to fetch them each time?

**Comment by erf** [comment]
I tried to read up on it, but i can't really wrap my head around it yet. I have previously used something similar to what explained [in this tutorial](https://www.raywenderlich.com/5456-in-app-purchase-tutorial-getting-started), search for the `purchasedProductIdentifiers` under the `Purchased Items` section.

**Comment by erf** [comment]
> You can also save the purchased information to UserDefaults and any databases if you want.
> However, you should consider that items are possible to be purchased by the same account in multi devices. So, I think it should not be saved in local databases.

If you are on multiple devices you would have to either Restore or try to Purchase the items again before saving them locally. It's cool if this also could be fixed, but it seem more like a minor inconvenience, since most people are on one device.

> I could not find IAPHelper.swift in the tutorial. Please see the implementation of IAPHelper#purchasedProductIdentifiers and ask the author if you want the details.

Hmm. Not sure what you mean, i was just proposing an example for how it could be done to store the purchases locally. Just search for `purchasedProductIdentifiers`.

**Comment by jinSasaki** [comment]
> If you are on multiple devices you would have to either Restore or try to Purchase the items again before saving them locally. It's cool if this also could be fixed, but it seem more like a minor inconvenience, since most people are on one device.

It is a minor inconvenience if your app does not need to consider multiple devices. However, this is a library. 
There are developers who consider the app is run in multiple iPhones,  in iPhone and iPad, or in a single device. I think a library should not depend on the app situation. 
So I have no plan that this library does not consider to purchase in multiple devices as far as Apple allows users to purchase in multiple devices.

I recommend you to fetch information from the receipt if you want to know purchased items.

> Hmm. Not sure what you mean, i was just proposing an example for how it could be done to store the purchases locally. Just search for purchasedProductIdentifiers.

Yeah, I found `purchasedProductIdentifiers` from that post, but `purchasedProductIdentifiers` is not provided by Apple's `StoreKit`. It is a property of `IAPHelper`. 
The post is not mine, so I do not know `IAPHelper.swift` implementation. 

Does it making sense?

**Comment by erf** [comment]
>  So I have no plan that this library does not consider to purchase in multiple devices as far as Apple allows users to purchase in multiple devices.

I understand.

> I recommend you to fetch information from the receipt if you want to know purchased items.

I look forwared to helper methods for the Receipt / SKReceiptRefreshRequest.

>  The post is not mine, so I do not know IAPHelper.swift implementation.

All the relevant code is explained inside the article, you can also download the source code from the bottom of the article if you sign in for a free account.
