### ISSUE TITLE
can we check given product is already purchased before? 

### ISSUE THREAD

**Issue by jignesh133** [jinSasaki/InAppPurchase#33]
**Is your feature request related to a problem? Please describe.**

can we check given product is already purchased before? 
we need to show restore Button based on his previous transaction

**Describe the solution you'd like**

create new method that will return the previous purchased product array

**Describe alternatives you've considered**
we need to make purchased request again an apple will handle

**Comment by jinSasaki** [comment]
You can check that the product is purchased by the receipt in the device.

Please see also #27
