### ISSUE TITLE
Purchase method's completion handler is not called

### ISSUE THREAD

**Issue by ArtSabintsev** [jinSasaki/InAppPurchase#39]
**Describe the bug**
Neither the `success` nor the `failure` are called. I've completed a successful purchase many times, but I can't do anything after the purchase has completed.

**To Reproduce**
My sample code.
```swift
    static func removeAds() {
        let iap = InAppPurchase.default
        iap.addTransactionObserver()
        iap.purchase(productIdentifier: "1") { result in
            switch result {
            case .success(let state):
                print("SUCCESS: \(state)")
                UserDefaults.standard.removeAds = true
            case .failure(let error):
                print(error)
            }
        }
        iap.removeTransactionObserver()
    }
```

Is something wrong my code?

**Screenshots**
![IMG_3627](https://user-images.githubusercontent.com/854860/63823704-bee10600-c922-11e9-9055-ba86b2fda95a.PNG)
![UNADJUSTEDNONRAW_thumb_55df](https://user-images.githubusercontent.com/854860/63823705-bee10600-c922-11e9-8b9c-98c78e3e519f.jpg)

**Desktop (please complete the following information):**
 - iOS 12

**Smartphone (please complete the following information):**
 - iOS 7 Device

**Comment by jinSasaki** [comment]
The In-App-Purchase transaction should be always observed after your app launched.
If you have no special reason, I recommend to call `addTransactionObserver`  in `didFinishLaunchingWithOptions` of `AppDelegate`, and not to remove the observer during your app running.

Thanks for the sample code to help me understand your issue!

**Comment by jinSasaki** [comment]
The latter is right.
`InAppPurchase.default` is a shared singleton instance.
