### ISSUE TITLE
Incorrect Carthage instructions

### ISSUE THREAD

**Issue by dchakarov** [jinSasaki/InAppPurchase#6]
In the Carthage section it should be `github "jinSasaki/in-app-purchase"` instead of `github "jinSasaki/InAppPurchase"`

**Comment by jinSasaki** [comment]
Thank you for your advice!
I renamed this repository name to `InAppPurchase`. 😄

**Comment by jinSasaki** [comment]
I think that this issue has been resolved.
If you have any questions, please create a new issue. Thank you!
